title: Guilherme Blog
description: Code, Ideas and Histories Drafts

url: "http://prokis.ch"
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: guilhermeprokisch
   twitter: guiprokisch
   facebook: guilherme.prokisch
   email: guilherme.prokich@gmail.com

google_analytics: "UA-58263416-1"
